name: ACTION

on:
  push:
    branches:
      - master
      - devops/pr
  pull_request:
    branches: 
      - master 

jobs:
  CI:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: --- checkout repo --- 
      uses: actions/checkout@v2

    - name: ----- Use Node.js ${{ matrix.node-version }} -----
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: --- install ---
      run: yarn

    - name: --- test ---
      # run: CI=true yarn test    
      run: echo "fake test, no test in yarn test"

    - name: --- build ---
      run:  yarn build
